# Generated by Django 5.2.8 on 2025-12-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token_created_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian tạo reset token', null=True),
        ),
    ]
