# Generated by Django 5.2.8 on 2025-12-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_reset_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token_created_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian tạo activation token', null=True),
        ),
    ]
